### ISSUE TITLE
Use Tapir

### ISSUE THREAD

**Issue by michaelbaudino** [alpinelab/website#3]
Use tapirgo.com to integrate a search engine

**Comment by tjouan** [comment]
Just FYI, https://github.com/matsimitsu/middleman-tapirgo repository is
archived on GitHub. And the URI in the README (http://tapirgo.com/) seems
"dead" right now:

    Failed to connect to tapirgo.com port 80: Connection refused

**Comment by michaelbaudino** [comment]
Yep, I think the defacto standard for that is Algolia now. Closing this.
